### PR TITLE
fix tests

### PR DESCRIPTION
**Pull request by marcoow**

### CODE REVIEW

**Comment by marcoow** [comment]
> @marcoow this will most likely either need a more recent version of ember-try or an update of ember-cli (recent Ember CLI releases include ember-try automatically)

just realized that as well ;)

> let me know if I should take over this PR

❤️ yes, please

**Comment by Turbo87** [comment]
I've thought a bit more about this PR, and I think it is probably not necessary to test all minor Ember releases with this addon since it's not doing anything special like using private API or an Handlebars AST transform. Instead I'd propose to follow the recommended pattern of testing against the last two LTS releases and stable/beta/canary (see https://github.com/ember-cli/ember-addon-output/blob/master/.travis.yml#L15-L20)

**Comment by marcoow** [comment]
> I've thought a bit more about this PR, and I think it is probably not necessary to test all minor Ember releases with this addon since it's not doing anything special like using private API or an Handlebars AST transform. Instead I'd propose to follow the recommended pattern of testing against the last two LTS releases and stable/beta/canary (see https://github.com/ember-cli/ember-addon-output/blob/master/.travis.yml#L15-L20)

Sounds like a good idea. Can you take over?

> Do we still care about v1.13 compatibility?

I'd say if we can support 1.13 without huge pains we should.

**Comment by Turbo87** [comment]
> Sounds like a good idea. Can you take over?

did that in #5 

> I'd say if we can support 1.13 without huge pains we should.

compared to https://github.com/ember-cli/ember-addon-output/blob/master/.travis.yml#L15-L20 I've kept the v1.13 test scenario in #5 so we should be able to support everything

I think the PR can be closed now in favor of #5

**Pull request closed without merging**
